# Site settings
title: oneSecondSmile
email: robert.snodgrass@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  oneSecondSmile - Bring down a blink of joy
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: https://twitter.com/Zeiganstrell
github_username:  RobertSnodgrass

# Build settings
markdown: kramdown

#If changes don't immediately come up, RESTART THE SERVER
